from django.db import models

# Create your models here.
class payslip(models.Model):
	ECR_no = models.CharField(max_length=30)
	Pan = models.CharField(max_length=50)
	empl_no = models.CharField(max_length=50,null=True)
	Name = models.CharField(max_length=100)
	Father = models.CharField(max_length=100)
	Desgn = models.CharField(max_length=100)
	Dept = models.CharField(max_length=100,null=True)
	acc_no = models.CharField(max_length=30)
	PF_ac = models.CharField(max_length=10)
	mo_inc = models.CharField(max_length=10)
	relief = models.CharField(max_length=15,null=True)
	basic_pay = models.FloatField()
	d_pay = models.FloatField()
	s_pay = models.FloatField()
	s_all = models.FloatField()
	p_pay = models.FloatField()
	da    = models.FloatField()
	i_relief = models.FloatField()
	nra = models.FloatField()
	ma = models.FloatField()
	ca = models.FloatField()
	wa = models.FloatField()
	ha = models.FloatField()
	misc = models.FloatField()
	total_pay = models.FloatField()
	pf = models.FloatField()
	apf = models.FloatField()
	pf_loan = models.FloatField()
	lic = models.FloatField()
	w_loan = models.FloatField()
	i_tax = models.FloatField()
	ebf = models.FloatField()
	con_adv = models.FloatField()
	hrc = models.FloatField()
	fc = models.FloatField()
	lc = models.FloatField()
	wc = models.FloatField()
	gss = models.FloatField()
	sbi_ln = models.FloatField()
	hb_loan = models.FloatField()
	rop = models.FloatField()
	uf = models.FloatField()
	elec_ch = models.FloatField()
	soc_ln = models.FloatField()
	m_loan = models.FloatField()
	f_adv = models.FloatField()
	gar_ch = models.FloatField()
	comp_ad = models.FloatField()
	car_chr = models.FloatField()
	misc2 = models.FloatField()
	total_ded = models.FloatField()
	net_pay = models.FloatField()
	month = models.CharField(max_length=6,null=True)
	year = models.IntegerField(null=True)
	

