# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-10 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ECR_no', models.CharField(max_length=30)),
                ('Pan', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Father', models.CharField(max_length=100)),
                ('Desgn', models.CharField(max_length=100)),
                ('acc_no', models.CharField(max_length=30)),
                ('PF_ac', models.CharField(max_length=10)),
                ('mo_inc', models.CharField(max_length=15)),
                ('basic_pay', models.CharField(max_length=15)),
                ('d_pay', models.CharField(max_length=10)),
                ('s_pay', models.CharField(max_length=10)),
                ('s_all', models.CharField(max_length=10)),
                ('p_pay', models.CharField(max_length=10)),
                ('da', models.CharField(max_length=10)),
                ('i_relief', models.CharField(max_length=10)),
                ('nra', models.CharField(max_length=10)),
                ('ma', models.CharField(max_length=10)),
                ('ca', models.CharField(max_length=10)),
                ('wa', models.CharField(max_length=10)),
                ('ha', models.CharField(max_length=10)),
                ('misc', models.CharField(max_length=10)),
                ('total_pay', models.CharField(max_length=10)),
                ('pf', models.CharField(max_length=10)),
                ('apf', models.CharField(max_length=10)),
                ('pf_loan', models.CharField(max_length=10)),
                ('lic', models.CharField(max_length=10)),
                ('w_loan', models.CharField(max_length=10)),
                ('i_tax', models.CharField(max_length=10)),
                ('ebf', models.CharField(max_length=10)),
                ('con_adv', models.CharField(max_length=10)),
                ('hrc', models.CharField(max_length=10)),
                ('fc', models.CharField(max_length=10)),
                ('lc', models.CharField(max_length=10)),
                ('wc', models.CharField(max_length=10)),
                ('gss', models.CharField(max_length=10)),
                ('sbi_ln', models.CharField(max_length=10)),
                ('hb_loan', models.CharField(max_length=10)),
                ('rop', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=10)),
                ('elec_ch', models.CharField(max_length=10)),
                ('soc_ln', models.CharField(max_length=10)),
                ('m_loan', models.CharField(max_length=10)),
                ('f_adv', models.CharField(max_length=10)),
                ('gar_ch', models.CharField(max_length=10)),
                ('comp_ad', models.CharField(max_length=10)),
                ('car_chr', models.CharField(max_length=10)),
                ('misc2', models.CharField(max_length=10)),
                ('total_ded', models.CharField(max_length=10)),
                ('net_pay', models.CharField(max_length=10)),
            ],
        ),
    ]
