# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-10 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180910_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='month',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
