# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-13 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_excelfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='created_at',
        ),
        migrations.AddField(
            model_name='payslip',
            name='Dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='empl_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='mo_inc',
            field=models.CharField(max_length=10),
        ),
    ]
