# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20180913_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ded', models.FloatField()),
                ('net_pay', models.FloatField()),
                ('month', models.CharField(max_length=6, null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
    ]
